name: onu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.0
  youtube_player_flutter: ^8.1.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/fin_pobreza.png
  - assets/logo_ods.png
  - assets/hambre_cero.png
  - assets/salud_bienestar.png
  - assets/educacion.png
